### PR TITLE
Upgrade to React Js 15.2.0

### PR DESCRIPTION
**Pull request by jacehensley-wf**
## Ultimate problem
React 15.1.0 had a performance regression in non-prod files. 15.2.0 fixes that regression.

## Solution
Upgrade to 15.2.0.

## Testing Suggestion
- Verify the tests pass
- Verify the examples render correctly

## Areas of Regression
None expected.

---
FYA: @trentgrover-wf @hleumas @greglittlefield-wf @clairesarsam-wf

### CODE REVIEW

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by aaronlademann-wf** [comment]
+1 

@trentgrover-wf this is ready for a merge / minor version bump.

**Comment by clairesarsam-wf** [comment]
+10

* Tests pass.
* Don't see any info in the ReactJS changelog for 15.2 that would necessitate other changes here.

**Comment by trentgrover-wf** [comment]
+1

**Pull request merged**
