### PR TITLE
Upgrade from `unittest` to `test` package

### PR DESCRIPTION
**Pull request by greglittlefield-wf**
### Ultimate Problem
#78: Tests used the deprecated `unittest` package, and had to be run manually.

### Solution
- Use the `test` package, which allows running tests via command-line and brings other features.
- Split js_interop_helpers tests into separate `_test.dart` files so they can be picked up automatically by `pub run test`

### Testing
* Run `pub run test -p content-shell,chrome`
* Verify that all unit tests run and pass.

### CODE REVIEW

**Comment by jacehensley-wf** [comment]
Should we set up dart_dev in this PR?

**Comment by jacehensley-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1
@trentgrover-wf

**Comment by trentgrover-wf** [comment]
@maxwellpeterson-wf I believe @greglittlefield-wf has all the keys to the kingdom on here now, so I am irrelevant :feelsgood:

**Pull request merged**
