### PR TITLE
Format all files with dartfmt

### PR DESCRIPTION
**Pull request by zfdavis**
[The Dart style guide](https://www.dartlang.org/guides/language/effective-dart/style#formatting) states that code should be formatted using the `dartfmt` tool. In fact, having non-formatted code is costing this repository points on [pub](https://pub.dartlang.org/packages/react#-analysis-tab-). All tests pass. I hope this branch will help this project do better on pub.

### CODE REVIEW

**Comment by greglittlefield-wf** [comment]
Thanks for the PR @zfdavis! I didn't realize dartfmt was part of that check. We also have definitely neglected the formatting in this repo...

Let me check with the team after the holiday to make sure we're cool with a line length of 80, and then I'll go ahead and merge! 

Have a happy New Year! 🎆

**Comment by greglittlefield-wf** [comment]
It seems that 80 is strongly recommended: https://github.com/dart-lang/pana/issues/468

**Comment by greglittlefield-wf** [comment]
Merging, thanks for the contribution!

**Comment by zfdavis** [comment]
No problem, I'm super happy to help out! This is actually the first open source project I've contributed to, so I'm glad to see it worked out.

**Pull request merged**
