### PR TITLE
Fixed in FireFox and still works in Chrome.

### PR DESCRIPTION
**Pull request by grumpy**

### CODE REVIEW

**Comment by grumpy** [comment]
@a

**Comment by hleumas** [comment]
Why have you closed this pull request @grumpy ?

**Comment by grumpy** [comment]
I mistakenly made the pull request to the main project and I had meant to make the request within my fork.  Sorry for not leaving a comment when I closed it.  Once I am sure I have a good fix I will request a new pull request.  I wasn't done with the fix yet, because I have not verified that it is fixed in IE yet.

**Comment by hleumas** [comment]
Ok, thanks:)

**Pull request closed without merging**
